name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - aansh

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of multi-agent-collab-learning are you running?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu
        - macOS
        - Windows
        - Other Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import the library with '...'
        2. Create a scenario with '...'
        3. Run the scenario '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        from multi_agent_collab_learning import ...

        # Your minimal reproduction code here
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: If applicable, copy and paste the full error message/traceback
      render: shell
      placeholder: Paste error output here...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information (GPU, CUDA version, PyTorch version, etc.)
      placeholder: |
        - PyTorch version: 2.0.0
        - CUDA version: 11.8
        - GPU: RTX 4090
        - Other relevant details...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, related issues, etc.)
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true