# Site Configuration
title: Multi-Agent Collaborative Learning
description: A comprehensive Python library for multi-agent collaborative learning scenarios
baseurl: "/multi-agent-collab-learning"
url: "https://docs.briefcasebrain.ai"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Mermaid support
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"

# Custom head scripts for Mermaid and styling
head_scripts: |
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}">
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'default',
      themeVariables: {
        primaryColor: '#3b82f6',
        primaryTextColor: '#1f2937',
        primaryBorderColor: '#2563eb',
        lineColor: '#6b7280',
        secondaryColor: '#f0f9ff',
        tertiaryColor: '#dbeafe',
        background: '#ffffff',
        mainBkg: '#ffffff'
      }
    });
  </script>

# Navigation
nav_external_links:
  - title: <i class="fas fa-arrow-left"></i> All Briefcase Brain Docs
    url: https://docs.briefcasebrain.ai
    hide_icon: true
  - title: <i class="fab fa-github"></i> GitHub Repository
    url: https://github.com/briefcasebrain/multi-agent-collab-learning
    hide_icon: true

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links
aux_links:
  "<i class='fas fa-home'></i> All Projects":
    - "https://docs.briefcasebrain.ai"
  "<i class='fab fa-github'></i> Source Code":
    - "https://github.com/briefcasebrain/multi-agent-collab-learning"
  "<i class='fas fa-download'></i> PyPI Package":
    - "#" # Will be updated when published

# Footer
footer_content: "Copyright &copy; 2024 Aansh Shah. Distributed under the MIT License."

# Code highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections for better organization
collections:
  scenarios:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_scenarios"
      type: "scenarios"
    values:
      layout: "default"
      parent: "Scenarios"
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: "default"
      parent: "Examples"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md