# Site Configuration
title: Multi-Agent Collaborative Learning
description: A comprehensive Python library for multi-agent collaborative learning scenarios
baseurl: "/multi-agent-collab-learning"
url: "https://docs.briefcasebrain.ai"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Mermaid support (built into just-the-docs theme)
mermaid:
  # Version of mermaid library - v10+ uses new API
  version: "10.6.1"

# Custom head includes are handled by _includes/head_custom.html

# Navigation
nav_external_links:
  - title: <i class="fas fa-arrow-left"></i> All Briefcase Brain Docs
    url: https://docs.briefcasebrain.ai
    hide_icon: true
  - title: <i class="fab fa-github"></i> GitHub Repository
    url: https://github.com/briefcasebrain/multi-agent-collab-learning
    hide_icon: true

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links
aux_links:
  "<i class='fas fa-home'></i> All Projects":
    - "https://docs.briefcasebrain.ai"
  "<i class='fab fa-github'></i> Source Code":
    - "https://github.com/briefcasebrain/multi-agent-collab-learning"
  "<i class='fas fa-download'></i> PyPI Package":
    - "#" # Will be updated when published

# Footer
footer_content: "Copyright &copy; 2024 Aansh Shah. Distributed under the MIT License."

# Code highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: false
  auto_ids: true
  hard_wrap: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: "1..6"
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections for better organization
collections:
  scenarios:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_scenarios"
      type: "scenarios"
    values:
      layout: "default"
      parent: "Scenarios"
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: "default"
      parent: "Examples"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md